const budgets={15:{static:85.38,ae:85.41,k:22,layer:17.32,speed:1.486,delta:.04,exits:[80.80,9.46,5.77,3.97]},20:{static:85.66,ae:85.53,k:19,layer:18.16,speed:1.399,delta:-.14,exits:[66.79,20.15,5.41,7.65]},25:{static:85.03,ae:84.94,k:17,layer:16.39,speed:1.573,delta:-.10,exits:[93.50,4.18,1.43,.88]},30:{static:83.20,ae:82.89,k:15,layer:17.16,speed:1.488,delta:-.31,exits:[84.61,7.05,3.00,5.35]}};
const fmtDelta=value=>`${value>=0?'+':'−'}${Math.abs(value).toFixed(2)} pp`;
function selectBudget(key){const data=budgets[key];document.querySelectorAll('[data-budget]').forEach(button=>button.setAttribute('aria-selected',String(button.dataset.budget===String(key))));document.querySelector('#budget-label').textContent=`${key}% compression`;document.querySelector('#static-score').textContent=`${data.static.toFixed(2)}%`;document.querySelector('#ae-score').textContent=`${data.ae.toFixed(2)}%`;document.querySelector('#prototype-count').textContent=`${data.k} / 28`;document.querySelector('#average-layer').textContent=data.layer.toFixed(2);document.querySelector('#own-speedup').textContent=`${data.speed.toFixed(3)}×`;document.querySelector('#accuracy-delta').textContent=fmtDelta(data.delta);const layers=[16,20,24,28];document.querySelector('#exit-bars').innerHTML=data.exits.map((value,index)=>`<div class="exit-bar"><b>${value.toFixed(1)}%</b><i style="height:${Math.max(3,value)}%"></i><span>L${layers[index]}</span></div>`).join('')}
document.querySelectorAll('[data-budget]').forEach(button=>button.addEventListener('click',()=>selectBudget(button.dataset.budget)));selectBudget(25);
function renderChart(){const host=document.querySelector('#budget-chart');const width=Math.max(520,host.clientWidth||620),height=310,pad={l:48,r:20,t:28,b:46};const xs=[15,20,25,30],ymin=80,ymax=87;const x=value=>pad.l+(value-15)/15*(width-pad.l-pad.r),y=value=>pad.t+(ymax-value)/(ymax-ymin)*(height-pad.t-pad.b);const path=field=>xs.map((key,index)=>`${index?'L':'M'} ${x(key)} ${y(budgets[key][field])}`).join(' ');const grid=[80,82,84,86].map(value=>`<line x1="${pad.l}" x2="${width-pad.r}" y1="${y(value)}" y2="${y(value)}"/><text x="${pad.l-10}" y="${y(value)+4}" text-anchor="end">${value}</text>`).join('');const ticks=xs.map(value=>`<text x="${x(value)}" y="${height-14}" text-anchor="middle">${value}%</text>`).join('');const points=field=>xs.map(value=>`<circle cx="${x(value)}" cy="${y(budgets[value][field])}" r="5"/>`).join('');host.innerHTML=`<svg viewBox="0 0 ${width} ${height}" aria-hidden="true"><g class="grid">${grid}${ticks}</g><line class="teacher" x1="${pad.l}" x2="${width-pad.r}" y1="${y(82.2947)}" y2="${y(82.2947)}"/><text class="teacher-label" x="${width-pad.r}" y="${y(82.2947)-7}" text-anchor="end">teacher 82.29</text><path class="series static" d="${path('static')}"/><g class="points static-points">${points('static')}</g><path class="series adaptive" d="${path('ae')}"/><g class="points adaptive-points">${points('ae')}</g><g class="legend"><circle cx="${pad.l}" cy="12" r="4"/><text x="${pad.l+10}" y="16">static FAD</text><circle class="adaptive-dot" cx="${pad.l+102}" cy="12" r="4"/><text x="${pad.l+112}" y="16">FAD-AE</text></g></svg>`}
renderChart();window.addEventListener('resize',renderChart);
const style=document.createElement('style');style.textContent='.chart svg{width:100%;height:auto}.chart .grid line{stroke:#d4d1c8;stroke-width:1}.chart text{font:11px ui-sans-serif;fill:#66707b}.chart .series{fill:none;stroke-width:3}.chart .static,.chart .static-points{stroke:#17202b;fill:#17202b}.chart .adaptive,.chart .adaptive-points,.chart .adaptive-dot{stroke:#ff6d4a;fill:#ff6d4a}.chart .teacher{stroke:#61a8a2;stroke-dasharray:6 5}.chart .teacher-label{fill:#398c85}.chart .legend text{font-weight:700}';document.head.append(style);
const html=document.documentElement,toggle=document.querySelector('#theme-toggle');const saved=localStorage.getItem('fad-theme');if(saved)html.dataset.theme=saved;toggle.addEventListener('click',()=>{html.dataset.theme=html.dataset.theme==='dark'?'light':'dark';localStorage.setItem('fad-theme',html.dataset.theme)});
document.querySelectorAll('.reveal').forEach(element=>element.classList.add('visible'));
